### ISSUE TITLE
Can you add PUID and PGID variables to docker-compose?

### ISSUE THREAD

**Issue by MrCee** [thomascenni/alpine-invoiceplane#2]
Hey this works great, I've been using it on Synology NAS for a while. I think since DSM 7.0 update we could use PUID and PGID to be set/mapped in the environment as these seem to be hardcoded as "1000" for both.
```
        environment:
            PUID: "1099"   
            PGID: "109"    
```
Is there any chance you could add this so the docker container runs as a user?
I'm using docker-compose and unless I'm missing something and could do this differently, It's the only thing that's missing.

**Comment by thomascenni** [comment]
Hello,
I can change on the docker-compose file to test, but I don't know if this can have an impact, because on the Docker file I have:

```
ARG PUID=1000
ARG PGID=1000
```
What do you think ?

**Comment by MrCee** [comment]
So this is exactly where I'm at. I'm still looking into it from my end also.  I am hoping I can help more later down the the track.

```
    app:
        image: "thomascenni/alpine-invoiceplane:v1.5.11"
        ports:
            - "11111:80"
        volumes:
            - /volume1/docker/invoiceplane/storage:/storage
            - /volume1/docker/invoiceplane/config:/config
        environment:
            IP_URL: "theURL.com"
            DB_HOSTNAME: db
            DB_USERNAME: "theusername"
            DB_PASSWORD: "thepassword"
            DB_DATABASE: "thedb"
            DB_PORT: "3306"
            TZ: "theTimeZone"
            PUID: "1099"                                                             
            PGID: "109"                                                              

```

if the PUID or PGID exists in the environment then set both or else default to the usual '1000' for each as you have coded

```
ARG PUID=$PUID
ARG PGID=$PGID
```
